### PR TITLE
Py3 support

### PR DESCRIPTION
**Pull request by MartinBasti**
Adding py2/3 support.

I couldn't create automatic tests due missing `koji.daemon` module: https://bugzilla.redhat.com/show_bug.cgi?id=1653270 and because koji py3 support is not complete yet:
https://pagure.io/koji/pull-request/1117

### CODE REVIEW

**Comment by MartinBasti** [comment]
Is py2.6 support still required? py2.6 test are failing, but it seems to be unrelated to my changes.

**Comment by twaugh** [comment]
LGTM. Not sure what to do about being unable to test.

**Comment by athos-ribeiro** [comment]
> Is py2.6 support still required? py2.6 test are failing, but it seems to be unrelated to my changes.

It would desirable to drop python 2.6 support then. Other than that, it LGTM

**Comment by MartinBasti** [comment]
@twaugh can I drop centos6 tests? We dropped py2.6 support in osbs-client anyway, so after upgrade this will stop working under py2.6.

**Comment by twaugh** [comment]
Fair point. OK, let's drop 2.6 testing then.

**Comment by MartinBasti** [comment]
Dropped

**Comment by athos-ribeiro** [comment]
LGTM

We can either rebase this now and wait for `kojid` port to include python3 tests in CI or add the CI tests and wait for `kojid` support to merge. It should be OK to do the former.

**Comment by MartinBasti** [comment]
I did manual testing with py3 koji cli and it worked (expected given that there are no changes in cli plugin and nobody from Fedora team complained). I'd go ahead and merge this.

**Comment by MartinBasti** [comment]
bump for review

**Comment by MartinBasti** [comment]
Release notes
> - code has been ported to py2/3 compatibility

**Pull request merged**
