### PR TITLE
Use osbs 'scratch' configuration for scratch builds

### LINKED ISSUE #53: Use a different osbs config section for scratch builds
Related: #51

### PR DESCRIPTION
**Pull request by vrutkovs**
Fixes #53

### CODE REVIEW

**Comment by vrutkovs** [comment]
Tested on my local koji instance, correct config section is used

**Comment by lcarva** [comment]
LGTM

**Comment by vrutkovs** [comment]
It doesn't seem to work atm - ```registries``` is always empty. It works when I start osbs via cli though, so this PR is incomplete

**Comment by vrutkovs** [comment]
Tested on a local koji instance - config is not being picked up correctly

**Comment by lcarva** [comment]
LGTM

**Pull request merged**
